/*
 * Generated by JasperReports - 7/30/09 8:24 AM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import net.sf.jasperreports.engine.*;
import java.util.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class rlt_horas_clientes_1248953081896_277378 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_dataFinal = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_dataInicial = null;
    private JRFillParameter parameter_parProjectUrl = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillField field_valorHoras = null;
    private JRFillField field_projeto = null;
    private JRFillField field_tipoHora = null;
    private JRFillField field_horaTerminoManha = null;
    private JRFillField field_horaInicioManha = null;
    private JRFillField field_valorDaHoraCliente = null;
    private JRFillField field_quantidadeHoras = null;
    private JRFillField field_valorDespesas = null;
    private JRFillField field_horaTerminoTarde = null;
    private JRFillField field_horaInicioTarde = null;
    private JRFillField field_recurso = null;
    private JRFillField field_dataApontamento = null;
    private JRFillField field_atividade = null;
    private JRFillField field_servicoExecutado = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_grp_consultor_COUNT = null;
    private JRFillVariable variable_grp_projeto_COUNT = null;
    private JRFillVariable variable_totalDespesaProjeto = null;
    private JRFillVariable variable_totalValorHoras = null;
    private JRFillVariable variable_horas = null;
    private JRFillVariable variable_minuto = null;
    private JRFillVariable variable_horasMinutos = null;
    private JRFillVariable variable_horasMinutos2 = null;
    private JRFillVariable variable_totalHorasConsultor = null;
    private JRFillVariable variable_horasConsultor = null;
    private JRFillVariable variable_minutosConsultor = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_dataFinal = (JRFillParameter)pm.get("dataFinal");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_dataInicial = (JRFillParameter)pm.get("dataInicial");
        parameter_parProjectUrl = (JRFillParameter)pm.get("parProjectUrl");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_valorHoras = (JRFillField)fm.get("valorHoras");
        field_projeto = (JRFillField)fm.get("projeto");
        field_tipoHora = (JRFillField)fm.get("tipoHora");
        field_horaTerminoManha = (JRFillField)fm.get("horaTerminoManha");
        field_horaInicioManha = (JRFillField)fm.get("horaInicioManha");
        field_valorDaHoraCliente = (JRFillField)fm.get("valorDaHoraCliente");
        field_quantidadeHoras = (JRFillField)fm.get("quantidadeHoras");
        field_valorDespesas = (JRFillField)fm.get("valorDespesas");
        field_horaTerminoTarde = (JRFillField)fm.get("horaTerminoTarde");
        field_horaInicioTarde = (JRFillField)fm.get("horaInicioTarde");
        field_recurso = (JRFillField)fm.get("recurso");
        field_dataApontamento = (JRFillField)fm.get("dataApontamento");
        field_atividade = (JRFillField)fm.get("atividade");
        field_servicoExecutado = (JRFillField)fm.get("servicoExecutado");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_grp_consultor_COUNT = (JRFillVariable)vm.get("grp_consultor_COUNT");
        variable_grp_projeto_COUNT = (JRFillVariable)vm.get("grp_projeto_COUNT");
        variable_totalDespesaProjeto = (JRFillVariable)vm.get("totalDespesaProjeto");
        variable_totalValorHoras = (JRFillVariable)vm.get("totalValorHoras");
        variable_horas = (JRFillVariable)vm.get("horas");
        variable_minuto = (JRFillVariable)vm.get("minuto");
        variable_horasMinutos = (JRFillVariable)vm.get("horasMinutos");
        variable_horasMinutos2 = (JRFillVariable)vm.get("horasMinutos2");
        variable_totalHorasConsultor = (JRFillVariable)vm.get("totalHorasConsultor");
        variable_horasConsultor = (JRFillVariable)vm.get("horasConsultor");
        variable_minutosConsultor = (JRFillVariable)vm.get("minutosConsultor");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_valorDespesas.getValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_valorHoras.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.Long)(new Long((((java.lang.Long)field_quantidadeHoras.getValue()).longValue()/ 1000) / 3600));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.Long)(new Long(((((java.lang.Long)field_quantidadeHoras.getValue()).longValue()/ 1000) % 3600) / 60));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)(((java.lang.Long)variable_horas.getValue()).longValue() < 10 ? "0" + ((java.lang.Long)variable_horas.getValue()).toString() : ((java.lang.Long)variable_horas.getValue()).toString());//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)(((java.lang.Long)variable_minuto.getValue()).longValue() < 10 ? "0" + ((java.lang.Long)variable_minuto.getValue()).toString() : ((java.lang.Long)variable_minuto.getValue()).toString());//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.Long)(((java.lang.Long)field_quantidadeHoras.getValue()));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.Long)(new Long((((java.lang.Long)variable_totalHorasConsultor.getValue()).longValue()/ 1000) / 3600));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.Long)(new Long(((((java.lang.Long)variable_totalHorasConsultor.getValue()).longValue()/ 1000) % 3600) / 60));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_recurso.getValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.Double)(new Double(((java.lang.Double)variable_totalDespesaProjeto.getValue()).doubleValue() + ((java.lang.Double)variable_totalValorHoras.getValue()).doubleValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_totalDespesaProjeto.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_totalValorHoras.getValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.String)((((java.lang.Long)variable_horasConsultor.getValue()).longValue() < 10 ? "0" + ((java.lang.Long)variable_horasConsultor.getValue()).toString() : ((java.lang.Long)variable_horasConsultor.getValue()).toString()) + ":" + ((((java.lang.Long)variable_minutosConsultor.getValue()).longValue() < 10 ? "0" + ((java.lang.Long)variable_minutosConsultor.getValue()).toString() : ((java.lang.Long)variable_minutosConsultor.getValue()).toString())));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_projeto.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.util.Date)(((java.util.Date)parameter_dataInicial.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.util.Date)(((java.util.Date)parameter_dataFinal.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_parProjectUrl.getValue())+ "imagens/logo.png");//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)field_recurso.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)field_projeto.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.util.Date)(((java.util.Date)field_dataApontamento.getValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.sql.Time)(((java.sql.Time)field_horaInicioManha.getValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.sql.Time)(((java.sql.Time)field_horaTerminoManha.getValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.sql.Time)(((java.sql.Time)field_horaInicioTarde.getValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.sql.Time)(((java.sql.Time)field_horaTerminoTarde.getValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.String)(((java.lang.String)field_servicoExecutado.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.String)(((java.lang.String)field_tipoHora.getValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_valorDaHoraCliente.getValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_valorHoras.getValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_valorDespesas.getValue()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.String)(((((java.lang.String)variable_horasMinutos.getValue()) + ":" + ((java.lang.String)variable_horasMinutos2.getValue())).equals("00:00")) ? "" : (((java.lang.String)variable_horasMinutos.getValue()) + ":" + ((java.lang.String)variable_horasMinutos2.getValue())));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.String)(((java.lang.String)field_atividade.getValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.util.Date)(new Date());//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)("GEPS - Gestão de Projetos Skilltec :: V0R1");//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)("/");//$JR_EXPR_ID=48$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_valorDespesas.getOldValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_valorHoras.getOldValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.Long)(new Long((((java.lang.Long)field_quantidadeHoras.getOldValue()).longValue()/ 1000) / 3600));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.Long)(new Long(((((java.lang.Long)field_quantidadeHoras.getOldValue()).longValue()/ 1000) % 3600) / 60));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)(((java.lang.Long)variable_horas.getOldValue()).longValue() < 10 ? "0" + ((java.lang.Long)variable_horas.getOldValue()).toString() : ((java.lang.Long)variable_horas.getOldValue()).toString());//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)(((java.lang.Long)variable_minuto.getOldValue()).longValue() < 10 ? "0" + ((java.lang.Long)variable_minuto.getOldValue()).toString() : ((java.lang.Long)variable_minuto.getOldValue()).toString());//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.Long)(((java.lang.Long)field_quantidadeHoras.getOldValue()));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.Long)(new Long((((java.lang.Long)variable_totalHorasConsultor.getOldValue()).longValue()/ 1000) / 3600));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.Long)(new Long(((((java.lang.Long)variable_totalHorasConsultor.getOldValue()).longValue()/ 1000) % 3600) / 60));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_recurso.getOldValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.Double)(new Double(((java.lang.Double)variable_totalDespesaProjeto.getOldValue()).doubleValue() + ((java.lang.Double)variable_totalValorHoras.getOldValue()).doubleValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_totalDespesaProjeto.getOldValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_totalValorHoras.getOldValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.String)((((java.lang.Long)variable_horasConsultor.getOldValue()).longValue() < 10 ? "0" + ((java.lang.Long)variable_horasConsultor.getOldValue()).toString() : ((java.lang.Long)variable_horasConsultor.getOldValue()).toString()) + ":" + ((((java.lang.Long)variable_minutosConsultor.getOldValue()).longValue() < 10 ? "0" + ((java.lang.Long)variable_minutosConsultor.getOldValue()).toString() : ((java.lang.Long)variable_minutosConsultor.getOldValue()).toString())));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_projeto.getOldValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.util.Date)(((java.util.Date)parameter_dataInicial.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.util.Date)(((java.util.Date)parameter_dataFinal.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_parProjectUrl.getValue())+ "imagens/logo.png");//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)field_recurso.getOldValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)field_projeto.getOldValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.util.Date)(((java.util.Date)field_dataApontamento.getOldValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.sql.Time)(((java.sql.Time)field_horaInicioManha.getOldValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.sql.Time)(((java.sql.Time)field_horaTerminoManha.getOldValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.sql.Time)(((java.sql.Time)field_horaInicioTarde.getOldValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.sql.Time)(((java.sql.Time)field_horaTerminoTarde.getOldValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.String)(((java.lang.String)field_servicoExecutado.getOldValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.String)(((java.lang.String)field_tipoHora.getOldValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_valorDaHoraCliente.getOldValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_valorHoras.getOldValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_valorDespesas.getOldValue()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.String)(((((java.lang.String)variable_horasMinutos.getOldValue()) + ":" + ((java.lang.String)variable_horasMinutos2.getOldValue())).equals("00:00")) ? "" : (((java.lang.String)variable_horasMinutos.getOldValue()) + ":" + ((java.lang.String)variable_horasMinutos2.getOldValue())));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.String)(((java.lang.String)field_atividade.getOldValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.util.Date)(new Date());//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)("GEPS - Gestão de Projetos Skilltec :: V0R1");//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)("/");//$JR_EXPR_ID=48$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_valorDespesas.getValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_valorHoras.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.Long)(new Long((((java.lang.Long)field_quantidadeHoras.getValue()).longValue()/ 1000) / 3600));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.Long)(new Long(((((java.lang.Long)field_quantidadeHoras.getValue()).longValue()/ 1000) % 3600) / 60));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.String)(((java.lang.Long)variable_horas.getEstimatedValue()).longValue() < 10 ? "0" + ((java.lang.Long)variable_horas.getEstimatedValue()).toString() : ((java.lang.Long)variable_horas.getEstimatedValue()).toString());//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)(((java.lang.Long)variable_minuto.getEstimatedValue()).longValue() < 10 ? "0" + ((java.lang.Long)variable_minuto.getEstimatedValue()).toString() : ((java.lang.Long)variable_minuto.getEstimatedValue()).toString());//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.Long)(((java.lang.Long)field_quantidadeHoras.getValue()));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.Long)(new Long((((java.lang.Long)variable_totalHorasConsultor.getEstimatedValue()).longValue()/ 1000) / 3600));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.Long)(new Long(((((java.lang.Long)variable_totalHorasConsultor.getEstimatedValue()).longValue()/ 1000) % 3600) / 60));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_recurso.getValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.Double)(new Double(((java.lang.Double)variable_totalDespesaProjeto.getEstimatedValue()).doubleValue() + ((java.lang.Double)variable_totalValorHoras.getEstimatedValue()).doubleValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_totalDespesaProjeto.getEstimatedValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_totalValorHoras.getEstimatedValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.String)((((java.lang.Long)variable_horasConsultor.getEstimatedValue()).longValue() < 10 ? "0" + ((java.lang.Long)variable_horasConsultor.getEstimatedValue()).toString() : ((java.lang.Long)variable_horasConsultor.getEstimatedValue()).toString()) + ":" + ((((java.lang.Long)variable_minutosConsultor.getEstimatedValue()).longValue() < 10 ? "0" + ((java.lang.Long)variable_minutosConsultor.getEstimatedValue()).toString() : ((java.lang.Long)variable_minutosConsultor.getEstimatedValue()).toString())));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.Object)(((java.lang.String)field_projeto.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.util.Date)(((java.util.Date)parameter_dataInicial.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.util.Date)(((java.util.Date)parameter_dataFinal.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_parProjectUrl.getValue())+ "imagens/logo.png");//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)field_recurso.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)field_projeto.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.util.Date)(((java.util.Date)field_dataApontamento.getValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.sql.Time)(((java.sql.Time)field_horaInicioManha.getValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.sql.Time)(((java.sql.Time)field_horaTerminoManha.getValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.sql.Time)(((java.sql.Time)field_horaInicioTarde.getValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.sql.Time)(((java.sql.Time)field_horaTerminoTarde.getValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.String)(((java.lang.String)field_servicoExecutado.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.String)(((java.lang.String)field_tipoHora.getValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_valorDaHoraCliente.getValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_valorHoras.getValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_valorDespesas.getValue()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.String)(((((java.lang.String)variable_horasMinutos.getEstimatedValue()) + ":" + ((java.lang.String)variable_horasMinutos2.getEstimatedValue())).equals("00:00")) ? "" : (((java.lang.String)variable_horasMinutos.getEstimatedValue()) + ":" + ((java.lang.String)variable_horasMinutos2.getEstimatedValue())));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.String)(((java.lang.String)field_atividade.getValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.util.Date)(new Date());//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.String)("GEPS - Gestão de Projetos Skilltec :: V0R1");//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)("/");//$JR_EXPR_ID=48$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
